"""Regenerate the IEEE paper's numeric content from YOUR experiment results.

    python scripts/export_paper_tables.py

Writes paper/tables/{macros,main_results,ablation,drift,split}.tex from reports/ and results/.
Then recompile paper/main.tex (pdflatex main.tex; bibtex main; pdflatex main.tex x2) or upload
the paper/ folder to Overleaf.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]


def f4(v, nd=4):
    try:
        if v is None or pd.isna(v):
            return "--"
        return f"{float(v):.{nd}f}"
    except (TypeError, ValueError):
        return str(v)


def g(v):
    return "--" if v is None else f"{float(v):g}"


def main(root: Path = ROOT) -> None:
    sys.path.insert(0, str(root))
    from src.config import get_paths, load_config
    paths = get_paths(load_config())          # honours SEMIVISION_ROOT / SEMIVISION_CONFIG
    R, T = paths.results, paths.root / "paper" / "tables"
    T.mkdir(parents=True, exist_ok=True)
    m1 = json.loads((R / "phase1" / "metrics.json").read_text())
    m2 = json.loads((R / "phase2" / "metrics.json").read_text())
    pol = json.loads((paths.phase2_dir / "rcc_policy.json").read_text())
    p1 = json.loads(paths.phase1_policy.read_text())
    ver = json.loads((R / "dataset" / "verification.json").read_text())
    rc = ver["split"]["role_counts"]
    l1, l2 = m1.get("localization") or {}, m2.get("localization") or {}

    # ---------------- macros used in the running text
    mac = {
        "NImages": ver["images_found"], "NRef": ver["empty_masks_reference"], "NAnom": ver["non_empty_masks_anomaly"],
        "NTest": rc["TEST"]["total"], "NTestRef": rc["TEST"]["reference"], "NTestAnom": rc["TEST"]["anomaly"],
        "NTrainRef": rc["TRAIN"]["total"], "CalN": pol["calibration_size"],
        "SelTopK": g(pol["topk"]), "SelLambda": g(pol["lambda"]), "SelAlpha": g(pol["alpha"]),
        "MinP": f4(pol.get("min_attainable_p")), "PoneThr": f"{p1['threshold']:.3g}",
    }
    for pre, m, loc in [("Pone", m1, l1), ("Ptwo", m2, l2)]:
        mac.update({f"{pre}AUC": f4(m["roc_auc"]), f"{pre}PRAUC": f4(m["pr_auc"]), f"{pre}Acc": f4(m["accuracy"]),
                    f"{pre}BA": f4(m["balanced_accuracy"]), f"{pre}Fone": f4(m["f1"]), f"{pre}Prec": f4(m["precision"]),
                    f"{pre}Rec": f4(m["recall"]), f"{pre}Spec": f4(m["specificity"]),
                    f"{pre}FPR": f4(m["fpr"]), f"{pre}FNR": f4(m["fnr"]), f"{pre}Cost": f4(m["cost_per_image"]),
                    f"{pre}FP": m["fp"], f"{pre}FN": m["fn"], f"{pre}TP": m["tp"], f"{pre}TN": m["tn"],
                    f"{pre}Dice": f4(loc.get("dice")), f"{pre}IoU": f4(loc.get("iou")),
                    f"{pre}PixAUC": f4(loc.get("pixel_auroc")), f"{pre}PixAP": f4(loc.get("pixel_ap"))})
    def _d(a, b):
        try:
            return float(b) - float(a)
        except (TypeError, ValueError):
            return None
    dd, di, dp = _d(l1.get("dice"), l2.get("dice")), _d(l1.get("iou"), l2.get("iou")), \
        _d(l1.get("pixel_auroc"), l2.get("pixel_auroc"))
    mac.update({
        "DeltaDice": f4(dd), "DeltaIoU": f4(di), "DeltaPixAUC": f4(dp),
        "DeltaDiceRel": f4(100 * dd / l1["dice"], 1) if dd is not None and l1.get("dice") else "--",
        "DeltaIoURel": f4(100 * di / l1["iou"], 1) if di is not None and l1.get("iou") else "--",
        "PixGapRed": f4(100 * dp / (1 - l1["pixel_auroc"]), 1) if dp is not None and l1.get("pixel_auroc", 1) < 1 else "--",
    })
    (T / "macros.tex").write_text("% AUTO-GENERATED by scripts/export_paper_tables.py\n" + "\n".join(
        f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in mac.items()) + "\n", encoding="utf-8")

    # ---------------- main results table
    rows = [("ROC-AUC", "roc_auc"), ("PR-AUC", "pr_auc"), ("Accuracy", "accuracy"),
            ("Balanced accuracy", "balanced_accuracy"), ("Precision", "precision"), ("Recall", "recall"),
            ("Specificity", "specificity"), ("F1-score", "f1"), ("FPR", "fpr"), ("FNR", "fnr"),
            ("Cost / image", "cost_per_image")]
    body = [f"{n} & {f4(m1[k])} & {f4(m2[k])} \\\\" for n, k in rows]
    body += ["\\midrule", f"TN / FP & {m1['tn']} / {m1['fp']} & {m2['tn']} / {m2['fp']} \\\\",
             f"FN / TP & {m1['fn']} / {m1['tp']} & {m2['fn']} / {m2['tp']} \\\\", "\\midrule"]
    body += [f"{n} & {f4(l1.get(k))} & {f4(l2.get(k))} \\\\" for n, k in
             [("Dice", "dice"), ("IoU", "iou"), ("Pixel AUROC", "pixel_auroc"), ("Pixel AP", "pixel_ap")]]
    (T / "main_results.tex").write_text(
        "% AUTO-GENERATED\n\\begin{tabular}{lcc}\n\\toprule\nMetric & Phase~1 ConvAE & RCC-ConvAE \\\\\n\\midrule\n"
        + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n", encoding="utf-8")

    # ---------------- ablation
    ab = pd.read_csv(R / "ablation" / "ablation.csv")
    lines = [f"{r.variant} & {f4(r.roc_auc)} & {f4(r.f1)} & {f4(r.balanced_accuracy)} & {f4(r.fpr)} & "
             f"{f4(r.fnr)} & {f4(r.cost_per_image)} & {f4(r.dice)} \\\\" for r in ab.itertuples()]
    (T / "ablation.tex").write_text(
        "% AUTO-GENERATED\n\\begin{tabular}{lccccccc}\n\\toprule\nVar. & AUC & F1 & BA & FPR & FNR & Cost & Dice \\\\\n"
        "\\midrule\n" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n", encoding="utf-8")

    # ---------------- drift
    ds = pd.read_csv(R / "drift" / "drift_summary.csv")
    lines = [f"{r.policy.replace('Phase1', 'P1').replace('Phase2', 'P2').replace('-recalibrated', '-recal')} & "
             f"{f4(r.mean_roc_auc)} & {f4(r.mean_balanced_accuracy)} & {f4(r.worst_balanced_accuracy)} & "
             f"{f4(r.mean_fpr)} & {f4(r.mean_fnr)} & {f4(r.mean_cost_per_image)} \\\\" for r in ds.itertuples()]
    (T / "drift.tex").write_text(
        "% AUTO-GENERATED\n\\begin{tabular}{lcccccc}\n\\toprule\nPolicy & AUC & BA & Worst BA & FPR & FNR & Cost \\\\\n"
        "\\midrule\n" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n", encoding="utf-8")

    # ---------------- split
    lines = [f"{k.replace('_', ' ').title()} & {v['reference']} & {v['anomaly']} & {v['total']} \\\\"
             for k, v in rc.items()]
    (T / "split.tex").write_text(
        "% AUTO-GENERATED\n\\begin{tabular}{lccc}\n\\toprule\nRole & Reference & Anomaly & Total \\\\\n\\midrule\n"
        + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n", encoding="utf-8")
    # copy result figures for the paper (included automatically if present)
    import shutil
    figdir = paths.root / "paper" / "figures"
    figdir.mkdir(parents=True, exist_ok=True)
    for name in ["roc_curve.png", "pr_curve.png", "localization_examples.png", "drift_balanced_accuracy.png",
                 "alpha_cost_curve.png", "ablation.png", "pvalue_distribution.png"]:
        if (paths.figures / name).exists():
            shutil.copy2(paths.figures / name, figdir / name)
    print(f"Paper tables + macros written to {T}; figures copied to {figdir}")


if __name__ == "__main__":
    main()
